package org.firstinspires.ftc.teamcode.OpModes.Auto; // This should match the file location. This is auto generated by Android Studio

import static com.pedropathing.api.Paths.curve;
import static com.pedropathing.api.Paths.line;

import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.seattlesolvers.solverslib.command.CommandOpMode;
import com.seattlesolvers.solverslib.command.SequentialCommandGroup;
import com.seattlesolvers.solverslib.pedroCommand.FollowPathCommand;

import org.firstinspires.ftc.teamcode.Hardware.RobotHardware;

@Autonomous
public class SampleChiciu extends CommandOpMode {

    private final RobotHardware robot = RobotHardware.getInstance();
    // pe docs va zice sa faceti instanta de follower dar noi o avem deja facuta in robothardware
    // (also urmati pasi de pe docs cand faceti auto ca ale noastre sunt deprecated mostly)

    private final PoseFactory p = PoseFactory.degrees(); // pose  factory chestie noua cititi docs e faina

    //poses
    private final Pose startPose = p.of(24, 24, 0);
    private final Pose park = p.of(48, 48, 90);
    // other poses...
    private final Pose controlPose = p.of(36, 60, 45);
    //paths
    private Path park() {
        return line(startPose, park).linear(startPose, park);
    }
    private Path curve_ex() {
        return curve(startPose, controlPose, park).linear(startPose, park);
    }
    @Override
    public void initialize() {
        super.reset();
        robot.init(hardwareMap, true);
        robot.follower.setPose(startPose);

        schedule(new SequentialCommandGroup(
                new FollowPathCommand(robot.follower, park())
        ));
    }

    @Override
    public void initialize_loop() {

    }

    @Override
    public void run() {
        super.run();
        robot.follower.update();
    }

    @Override
    public void reset() {                       // called at end of opmode, even on early stop -- resets scheduler ahead and saves pose to lastAutopose for teleop pass on
        if (robot.follower != null) RobotHardware.lastAutoPose = robot.follower.pose();
        super.reset();
    }
}